services:
  backend:
    build: ./backend
    restart: unless-stopped
    expose:
      - "5000"

  frontend:
    build: ./frontend
    ports:
      - "${PORT_HTTP:-8874}:80"
      - "${PORT_HTTPS:-8875}:443"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
      - "./nginx/ssl_password.txt:/etc/nginx/ssl/ssl_password.txt:ro"
      - "${SSL_CERT_PATH}:/etc/nginx/ssl/server.crt:ro"
      - "${SSL_KEY_PATH}:/etc/nginx/ssl/server.key:ro"
    depends_on:
      - backend
    restart: unless-stopped
